export const AUTHENTICATE = 'AUTHENTICATE'
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED'
export const DEAUTHENTICATE = 'DEAUTHENTICATE'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST'
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS'
export const GET_PHOTOS_FAILED = 'GET_PHOTOS_FAILED'
export const GET_SINGLE_PHOTO = 'GET_SINGLE_PHOTO'
export const GET_UPLOADS_SUCCESS = 'GET_UPLOADS_SUCCESS'

export const HANDLE_DEMO_REQUEST = 'HANDLE_DEMO_REQUEST'
export const HANDLE_DEMO_SUCCESS = 'HANDLE_DEMO_SUCCESS'
export const HANDLE_DEMO_FAILED = 'HANDLE_DEMO_FAILED'

export const ADD_PHOTO_REQUEST = 'ADD_PHOTO_REQUEST'
export const ADD_PHOTO_SUCCESS = 'ADD_PHOTO_SUCCESS'
export const ADD_PHOTO_FAILED = 'ADD_PHOTO_FAILED'

export const HANDLE_SEARCH_REQUEST = 'HANDLE_SEARCH_REQUEST'
export const HANDLE_SEARCH_SUCCESS = 'HANDLE_SEARCH_SUCCESS'
export const HANDLE_SEARCH_FAILED = 'HANDLE_SEARCH_FAILED'