export const AUTHENTICATE = 'AUTHENTICATE'
export const DEAUTHENTICATE = 'DEAUTHENTICATE'

export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST'
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS'
export const GET_PHOTOS_FAILED = 'GET_PHOTOS_FAILED'
export const GET_SINGLE_PHOTO = 'GET_SINGLE_PHOTO'
export const GET_UPLOADS_SUCCESS = 'GET_UPLOADS_SUCCESS'